CREATE TABLE IF NOT EXISTS rentals(
id SERIAL PRIMARY KEY,
user_id INT FOREIGN KEY REFERENCES users(id),
book_id INT FOREIGN KEY REFERENCES books(id),
quantity INT NOT NULL,
`status` BOOLEAN DEFAULT 1,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);